final dummyData = [
  {
    "number": 1,
    "letter": "あ",
    "onomatopoeia": "あいあい",
    "transliteration": "ai-ai",
    "frequency": "Antiquated",
    "meaningjp": "哀哀。深く悲しむさま。悲しく哀れなさま。",
    "meaningen": "deep sadness, sorrow",
    "mainemotion": "sad",
    "subemotion": "despair"
  },
  {
    "number": 2,
    "letter": "あ",
    "onomatopoeia": "あいたい",
    "transliteration": "ai-tai",
    "frequency": "Antiquated",
    "meaningjp": "靉靆。気持ちや表情などの晴れ晴れしないさま。陰気なさま。",
    "meaningen": "in a gloomy, sad state",
    "mainemotion": "sad",
    "subemotion": "depressed"
  },
  {
    "number": 3,
    "letter": "あ",
    "onomatopoeia": "あくせく",
    "transliteration": "aku-seku",
    "frequency": "Common",
    "meaningjp": "齷齪。細かいことを気にして、落ち着かないさま。目先のことにとらわれて、気持ちがせかせかするさま。",
    "meaningen": "worried about the small things, stressed about immediate problems. Emotionally overwhelmed",
    "mainemotion": "bad",
    "subemotion": "stressed"
  },
  {
    "number": 4,
    "letter": "あ",
    "onomatopoeia": "あけらかん",
    "transliteration": "akerakan",
    "frequency": "Common",
    "meaningjp": "呆れたり何かに気を取られたりして、口を閉じるのをわすれるさま。",
    "meaningen": "bored, zoned out, mouth open",
    "mainemotion": "bad",
    "subemotion": "tired"
  },
  {
    "number": 5,
    "letter": "あ",
    "onomatopoeia": "あたふた",
    "transliteration": "ata-futa",
    "frequency": "Common",
    "meaningjp": "ひどく慌てるさま。",
    "meaningen": "terribly surprised, flown into a shock",
    "mainemotion": "surprised",
    "subemotion": "startled"
  },
  {
    "number": 6,
    "letter": "あ",
    "onomatopoeia": "あっか",
    "transliteration": "akka",
    "feature": "古",
    "frequency": "Antiquated",
    "meaningjp": "あるものに心を奪われて、口を開けたままでいるさま。",
    "meaningen": "smitten; taken aback, mouth agape",
    "mainemotion": "surprised",
    "subemotion": "amazed"
  },
  {
    "number": 7,
    "letter": "あ",
    "onomatopoeia": "あっけらかん",
    "transliteration": "akkerakan",
    "frequency": "Common",
    "meaningjp": "意外な状況に直面したり、呆れ果てりして放心状態にある様。",
    "meaningen": "dazed, astonished by an unexpected situation",
    "mainemotion": "surprised",
    "subemotion": "startled"
  },
  {
    "number": 9,
    "letter": "あ",
    "onomatopoeia": "あっはっは",
    "transliteration": "ahha-hha",
    "frequency": "Common",
    "meaningjp": "快活に大声で笑う声。また、そのさま。",
    "meaningen": "A state or sound of laughing cheerfully",
    "mainemotion": "happy",
    "subemotion": "content"
  },
  {
    "number": 10,
    "letter": "あ",
    "onomatopoeia": "あっぱとっぱ",
    "transliteration": "appa-toppa",
    "frequency": "Antiquated",
    "meaningjp": "慌てふためくさま。",
    "meaningen": "in a state of panic, fumbling about",
    "mainemotion": "surprised",
    "subemotion": "startled"
  },
  {
    "number": 11,
    "letter": "あ",
    "onomatopoeia": "あっぱらぱー",
    "transliteration": "appa-rapa",
    "frequency": "Antiquated",
    "meaningjp": "ものごとを深く考えないさま。また、そのような人。",
    "meaningen": "happy-go-lucky, a person who does not think deeply",
    "mainemotion": "happy",
    "subemotion": "trusting"
  },
  {
    "number": 12,
    "letter": "あ",
    "onomatopoeia": "あっはん",
    "transliteration": "ahhan",
    "feature": "茨城の方言・Ibaraki dialect",
    "frequency": "Infrequent",
    "meaningjp": "性的に興奮しているという態度を示すさま。色っぽい声の一種。",
    "meaningen": "In an Ibaraki dialect; A woman displaying sexual arousal or making a sexually suggestive sound",
    "mainemotion": "happy",
    "subemotion": "playful"
  },
  {
    "number": 13,
    "letter": "あ",
    "onomatopoeia": "あっぷあっぷ",
    "transliteration": "appu-appu",
    "frequency": "Common",
    "meaningjp": "水におぼれて苦しむ様子。困難に苦しむ様子。",
    "meaningen": "Suffering from drowning in water. Suffering from various difficulties",
    "mainemotion": "bad",
    "subemotion": "hurt"
  },
  {
    "number": 14,
    "letter": "あ",
    "onomatopoeia": "あっぺとっぺ",
    "transliteration": "appe-toppe",
    "feature": "宮城の方言・Miyagi dialect",
    "frequency": "Antiquated",
    "meaningjp": "話の辻褄が合わないさま",
    "meaningen": "In a Miyagi dialect; Vague and unclear, a person whose story is all over the place",
    "mainemotion": "surprised",
    "subemotion": "confused"
  },
  {
    "number": 15,
    "letter": "あ",
    "onomatopoeia": "あはあは",
    "transliteration": "aha-aha",
    "frequency": "Common",
    "meaningjp": "口をあけて無遠慮うに笑う声。また、そのさま。",
    "meaningen": "The state or sound of laughing without inhibition",
    "mainemotion": "happy",
    "subemotion": "content"
  },
  {
    "number": 16,
    "letter": "あ",
    "onomatopoeia": "あばあば",
    "transliteration": "aba-aba",
    "feature": "新潟県の方言・Niigata dialect",
    "frequency": "Antiquated",
    "meaningjp": "新潟県の方言で、水におぼれて苦しむ様子。困難に苦しむ様子。",
    "meaningen": "In a Niigata dialect; Suffering from drowning in water. Suffering from various difficulties",
    "mainemotion": "bad",
    "subemotion": "hurt"
  },
  {
    "number": 17,
    "letter": "あ",
    "onomatopoeia": "あばちゃば",
    "transliteration": "aba-chaba",
    "frequency": "Antiquated",
    "meaningjp": "あわててうろたえるさま。",
    "meaningen": "Panicked and flustered, fumbling about in a panic",
    "mainemotion": "bad",
    "subemotion": "stressed"
  },
  {
    "number": 18,
    "letter": "あ",
    "onomatopoeia": "あはは",
    "transliteration": "aha-ha",
    "frequency": "Common",
    "meaningjp": "口を大きく開けて高く笑う声。また、そのさま。",
    "meaningen": "The state of sound of opening one's mouth widely while laughing",
    "mainemotion": "happy",
    "subemotion": "content"
  },
  {
    "number": 19,
    "letter": "あ",
    "onomatopoeia": "あぶあぶ",
    "transliteration": "abu-abu",
    "frequency": "Antiquated",
    "meaningjp": "あやぶむ気持ちのはなはだしいさま。恐れ気づかうさま。",
    "meaningen": "Extreme fear and trepidation",
    "mainemotion": "fearful",
    "subemotion": "scared"
  },
  {
    "number": 20,
    "letter": "あ",
    "onomatopoeia": "あぷあぷ",
    "transliteration": "apu-apu",
    "frequency": "Infrequent",
    "meaningjp": "呼吸が苦しくなり、口を大きく開け閉めして吸ったり吐いたりするさま。困難に追いつめられて苦しむさま。",
    "meaningen": "Rapidly breathing in and out from drowning in water. Plagued with difficulties",
    "mainemotion": "bad",
    "subemotion": "hurt"
  },
  {
    "number": 21,
    "letter": "あ",
    "onomatopoeia": "あへあへ",
    "transliteration": "ahe-ahe",
    "frequency": "Infrequent",
    "meaningjp": "息苦しそうなさま。性的にもだえるさま。",
    "meaningen": "Feeling short of breath. Writhing in a sexual manner",
    "mainemotion": "surprised",
    "subemotion": "excited"
  },
  {
    "number": 22,
    "letter": "あ",
    "onomatopoeia": "あやふや",
    "transliteration": "aya-fuya",
    "frequency": "Common",
    "meaningjp": "ものごとが確かでないさま。あいまいで判断のつかないさま。いずれとも決定しないさま。",
    "meaningen": "Unsure and indecisive.",
    "mainemotion": "surprised",
    "subemotion": "confused"
  },
  {
    "number": 23,
    "letter": "あ",
    "onomatopoeia": "あわあわ",
    "transliteration": "awa-awa",
    "frequency": "Infrequent",
    "meaningjp": "余裕を失って、ものが手につかないさま。",
    "meaningen": "Losing one's composure, losing one's grip on themselves",
    "mainemotion": "bad",
    "subemotion": "stressed"
  },
  {
    "number": 24,
    "letter": "あ",
    "onomatopoeia": "あわわ",
    "transliteration": "awa-wa",
    "frequency": "Infrequent",
    "meaningjp": "急に気づいたり、驚いたり、事をしそこないそうになって、思わず声を発するさま。",
    "meaningen": "Shocked, letting out an involuntary gasp of surprise",
    "mainemotion": "surprised",
    "subemotion": "startled"
  },
  {
    "number": 25,
    "letter": "あ",
    "onomatopoeia": "あんあん",
    "transliteration": "an-an",
    "frequency": "Common",
    "meaningjp": "人が大きな声をあげてなく声。また、そのさま。",
    "meaningen": "The state or sound of someone wailing loudly",
    "mainemotion": "sad",
    "subemotion": "despair"
  },
  {
    "number": 26,
    "letter": "あ",
    "onomatopoeia": "あんぐり",
    "transliteration": "an-guri",
    "frequency": "Common",
    "meaningjp": "驚いたり、あきれたり、放心して、思わず口をあけたままにする様子。",
    "meaningen": "Dumbfounded, shocked speechless",
    "mainemotion": "surprised",
    "subemotion": "startled"
  },
  {
    "number": 27,
    "letter": "あ",
    "onomatopoeia": "あんけあんけあんけあんけあんけあんけ",
    "transliteration": "an-ke",
    "feature": "古",
    "frequency": "Antiquated",
    "meaningjp": "放心のあまり、口を開けっぱなしにしているさま。",
    "meaningen": "In a daze, mouth agape",
    "mainemotion": "surprised",
    "subemotion": "startled"
  }
];